### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by Hatrison** [olehmartynenko/self_regex#6]
1.For better user experience add Home page where user can choose between “Match” and “Replace”

2.https://github.com/olehmartynenko/self_regex/blob/main/backend/server.py#L28 Put port in constant.

3.https://github.com/olehmartynenko/self_regex/blob/main/backend/server.py#L15 https://github.com/olehmartynenko/self_regex/blob/main/backend/server.py#L24 Remove unnecessary prints.

**Comment by olehmartynenko** [comment]
Everything was fixed/implemented in https://github.com/olehmartynenko/self_regex/pull/8
